### ISSUE TITLE
Missing color for types in PHP

### ISSUE THREAD

**Issue by Kaspik** [arzg/xcode-theme#1]
Hey! Thanks for this theme that I use because as an iOS dev I'm used to Xcode.

I noticed lately some changes (mainly for V7, nice update) but still no fix for one thing - Xcode uses light purple for types like `UIImage` or `UIBarButtonItem` (viz screenshot) where your theme is using white the same as for properties (like `IntlDateFormatter` or `DateTime`). Are you aware / planning to update this?

Thanks!

Xcode
<img width="878" alt="Screenshot 2022-05-21 at 17 30 07" src="https://user-images.githubusercontent.com/7204168/169658546-7e132fb1-8557-4d9f-8b4d-b40e83b186d2.png">

PHP
<img width="863" alt="v7" src="https://user-images.githubusercontent.com/7204168/169658306-05bc9d12-661e-40c2-be76-39b7f5338d55.png">

**Comment by lunacookies** [comment]
I have no idea if you’re still using this theme, but greatly improved PHP highlighting is now up in v0.7.13 :)
